server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://pg:5432/postgres
    username: postgres
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: users.events

springdoc:
  packages-to-scan: com.example.userservice.controller
  paths-to-exclude: /ui/**
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: user-service

logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO
