server:
  port: 8888
  address: 0.0.0.0

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: file:/config-repo
management:
  endpoints:
    web:
      exposure:
        include: health,info,env